import { Message as M } from './message';

export const CZECH = {
  [M.ACTIVE_FILTERS]: 'Aktivní filtry',
  [M.ADD_TO_FILTER]: 'Přidat k filtru',
  [M.ADVANCED_SEARCH]: 'Pokročilé vyhledávání',
  [M.ALL_FILTERS]: 'Všechny filtry',
  [M.ARCH_DESC]: 'Archiválie',
  [M.ARCH_DESC_DAO_ONLY]: 'Archiválie - pouze s digitalizáty',
  [M.ARCHIVE]: 'Archiv',
  [M.BASIC_INFORMATION]: 'Základní informace',
  [M.CANCEL]: 'Zrušit',
  [M.CENTER]: 'Vycentrovat',
  [M.CONFIRM]: 'Potvrdit',
  [M.CONTACT]: 'Kontakt',
  [M.CLOSE]: 'Zavřít',
  [M.CLICK_TO_COLLAPSE]: 'Kliknutím sbalte',
  [M.CLICK_TO_EXPAND]: 'Kliknutím rosbalte',
  [M.DIGITIZER]: 'Digitalizát',
  [M.DIGITIZERS]: 'Digitalizáty',
  [M.DISPLAY]: 'Zobrazit',
  [M.DOWNLOAD]: 'Stáhnout',
  [M.DOWNLOAD_ALL]: 'Stáhnout vše',
  [M.DOWNLOAD_METADATA]: 'Stáhnout metadata',
  [M.ENTER_SEARCH_QUERY]: 'Zadejte hledaný dotaz',
  [M.ENTER_THE_RANGE]: 'Zadat rozpětí',
  [M.ENTITY]: 'Přístupové body',
  [M.FAVOURITE_QUERIES]: 'Oblíbené dotazy',
  [M.FILE]: 'Soubor',
  [M.FILES_IN_DAO]: 'Soubory v DAO',
  [M.FIND_RELATED]: 'Najít související',
  [M.FINDING_AID]: 'Archivní pomůcky',
  [M.FROM]: 'Od',
  [M.FUND]: 'Archivní soubory',
  [M.FROM]: 'Od',
  [M.HELP]: 'Nápověda',
  [M.INTRODUCTION]: 'Úvod',
  [M.LIST_OF_DAO]: 'Seznam DAO',
  [M.NEW_FILTER]: 'Nový filtr',
  [M.NEWS]: 'Aktuality',
  [M.NEXT_PAGE]: 'Další strana',
  [M.NO_ITEMS_FOUND]:
    'Žádné položky nenalezeny. Zkuste změnit zadaná kritéria.',
  [M.ONLINE]: 'Online',
  [M.OTHER_DIGITIZERS]: 'Další digitalizáty',
  [M.PER_PAGE]: 'Počet na stránce',
  [M.PREVIOUS_PAGE]: 'Předchozí strana',
  [M.RELATIONSHIP_NOT_FOUND]: 'Žádný vztah nebyl nalezen',
  [M.RELATIONSHIP_TYPE_CONSTRAINT]: 'Omezení typu vztahu',
  [M.RELATIONSHIPS]: 'Vztahy',
  [M.SEARCH]: 'Vyhledávání',
  [M.SEARCH_BTN]: 'Hledat',
  [M.SHOW_LESS]: 'Zobrazit méně',
  [M.SHOW_MORE]: 'Zobrazit více',
  [M.TO]: 'Do',
  [M.ZOOM_IN]: 'Přiblížit',
  [M.ZOOM_OUT]: 'Oddálit',
};
