import { Message as M } from './message';

export const ENGLISH = {
  [M.ACTIVE_FILTERS]: 'Active filters',
  [M.ADD_TO_FILTER]: 'Add to filter',
  [M.ADVANCED_SEARCH]: 'Advanced search',
  [M.ALL_FILTERS]: 'All filters',
  [M.ARCH_DESC]: 'Archival material',
  [M.ARCH_DESC_DAO_ONLY]: 'Archival material - digital objects only',
  [M.ARCHIVE]: 'Archive',
  [M.BASIC_INFORMATION]: 'Basic information',
  [M.CANCEL]: 'Cancel',
  [M.CENTER]: 'Center',
  [M.CONFIRM]: 'Confirm',
  [M.CONTACT]: 'Contact',
  [M.CLOSE]: 'Close',
  [M.CLICK_TO_COLLAPSE]: 'Click to collapse',
  [M.CLICK_TO_EXPAND]: 'Click to expand',
  [M.DIGITIZER]: 'Digitizer',
  [M.DIGITIZERS]: 'Digitizers',
  [M.DISPLAY]: 'Display',
  [M.DOWNLOAD]: 'Download',
  [M.DOWNLOAD_ALL]: 'Download all',
  [M.DOWNLOAD_METADATA]: 'Download metadata',
  [M.ENTER_SEARCH_QUERY]: 'Enter a search query',
  [M.ENTER_THE_RANGE]: 'Enter the range',
  [M.ENTITY]: 'Entities',
  [M.FAVOURITE_QUERIES]: 'Favourite queries',
  [M.FILE]: 'File',
  [M.FILES_IN_DAO]: 'Files in DAO',
  [M.FIND_RELATED]: 'Find related',
  [M.FINDING_AID]: 'Finding aids',
  [M.FROM]: 'From',
  [M.FUND]: 'Funds',
  [M.FROM]: 'From',
  [M.HELP]: 'Help',
  [M.INTRODUCTION]: 'Introduction',
  [M.LIST_OF_DAO]: 'List of DAO',
  [M.NEW_FILTER]: 'New filter',
  [M.NEWS]: 'News',
  [M.NEXT_PAGE]: 'Next page',
  [M.NO_ITEMS_FOUND]: 'No items found. Try changing the entered criteria.',
  [M.ONLINE]: 'Online',
  [M.OTHER_DIGITIZERS]: 'Other digitizers',
  [M.PER_PAGE]: 'Per page',
  [M.PREVIOUS_PAGE]: 'Previous page',
  [M.RELATIONSHIP_NOT_FOUND]: 'Relationships not found',
  [M.RELATIONSHIP_TYPE_CONSTRAINT]: 'Relationship type constraint',
  [M.RELATIONSHIPS]: 'Relationships',
  [M.SEARCH]: 'Search',
  [M.SEARCH_BTN]: 'Search',
  [M.SHOW_LESS]: 'Show less',
  [M.SHOW_MORE]: 'Show more',
  [M.TO]: 'To',
  [M.ZOOM_IN]: 'Zoom in',
  [M.ZOOM_OUT]: 'Zoom out',
};
