import { Message as M } from './message';

export const GERMAN = {
  [M.ACTIVE_FILTERS]: 'Active filters',
  [M.ADD_TO_FILTER]: 'Add to filter',
  [M.ADVANCED_SEARCH]: 'Advanced search',
  [M.ALL_FILTERS]: 'All filters',
  [M.APP_LOADING_FAILED]: 'Error: Failed to load app.',
  [M.ARCH_DESC]: 'Archival material',
  [M.ARCH_DESC_DAO_ONLY]: 'Archival material - digital objects only',
  [M.ARCHIVE]: 'Archive',
  [M.ARCHIVES]: 'Archives',
  [M.ATTACHMENTS]: 'Attachments',
  [M.BASIC_INFORMATION]: 'Basic information',
  [M.CANCEL]: 'Cancel',
  [M.CENTER]: 'Center',
  [M.CONFIRM]: 'Confirm',
  [M.CONTACT]: 'Contact',
  [M.CLOSE]: 'Close',
  [M.CLICK_TO_COLLAPSE]: 'Click to collapse',
  [M.CLICK_TO_EXPAND]: 'Click to expand',
  [M.DAO]: 'digital object',
  [M.DAO_ONLY]: 'Digital objects only',
  [M.DAOS]: 'Digital objects',
  [M.DISPLAY]: 'Display',
  [M.DOWNLOAD]: 'Download',
  [M.DOWNLOAD_ALL]: 'Download all',
  [M.DOWNLOAD_METADATA]: 'Download metadata',
  [M.ENTER_THE_RANGE]: 'Enter the range',
  [M.ENTITY]: 'Entities',
  [M.ERROR_DOWNLOAD_FILE]: 'Error: Failed to download file.',
  [M.FAVOURITE_QUERIES]: 'Favourite queries',
  [M.FILE]: 'file',
  [M.FILES_IN_DAO]: 'Files in DAO',
  [M.FIND_RELATED]: 'Find related',
  [M.FINDING_AID]: 'Finding aids',
  [M.FROM]: 'From',
  [M.FUND]: 'Funds',
  [M.FROM]: 'From',
  [M.HELP]: 'Help',
  [M.INACTIVE]: 'inactive',
  [M.INTRODUCTION]: 'Introduction',
  [M.LIST_OF_DAO]: 'List of DAO',
  [M.NEW_FILTER]: 'New filter',
  [M.NEWS]: 'News',
  [M.NEXT_PAGE]: 'Next page',
  [M.NO_FILES_TO_DISPLAY]: 'No files to display',
  [M.NO_ITEMS_FOUND]: 'No items found. Try changing the entered criteria.',
  [M.ONLINE]: 'Online',
  [M.ORIGINATORS]: 'Originators',
  [M.OTHER_DAOS]: 'Other digital objects',
  [M.PER_PAGE]: 'Per page',
  [M.PREVIOUS_PAGE]: 'Previous page',
  [M.RELATED_TO]: 'Related to',
  [M.RELATIONSHIP_NOT_FOUND]: 'Relationships not found',
  [M.RELATIONSHIP_TYPE_CONSTRAINT]: 'Relationship type constraint',
  [M.RELATIONSHIPS]: 'Relationships',
  [M.REMOVE_FILTERS]: 'Remove filters',
  [M.SEARCH]: 'Search',
  [M.SEARCH_ARCH_DESC]: 'Search in archival materials',
  [M.SEARCH_ARCH_DESC_DAO_ONLY]:
    'Search in archival materials with digital objects only',
  [M.SEARCH_BTN]: 'Search',
  [M.SEARCH_ENTITY]: 'Search in in index entries and keywords',
  [M.SEARCH_FINDING_AID]: 'Search in archival lists',
  [M.SEARCH_FUND]: 'Search in funds',
  [M.SEARCH_NO_FILTER]: 'Search without filter',
  [M.SHARE_THROUGH_EMAIL]: 'Share through e-mail',
  [M.SHARE_THROUGH_FACEBOOK]: 'Share on Facebook',
  [M.SHARE_THROUGH_TWITTER]: 'Share on Twitter',
  [M.SHOW_LESS]: 'Show less',
  [M.SHOW_MORE]: 'Show more',
  [M.TEXT_ARCH_DESC]: 'Search for specific archives and digital objects',
  [M.TEXT_ENTITY]: 'Search archives using index entries and keywords',
  [M.TEXT_FINDING_AID]: 'Search in archival lists',
  [M.TEXT_FUND]: 'Searching for archives and collections',
  [M.TO]: 'To',
  [M.TOO_MANY_RESULTS]: 'Too many results?',
  [M.TREE_VIEW_CURRENT_STATE]: 'View of the whole AS (current state)',
  [M.TRY_REFINING_YOUR_SEARCH_AREA]: 'Try refining your search area',
  [M.URL_TOO_LONG]: 'URL is too long, no more filters can be added.',
  [M.ZOOM_IN]: 'Zoom in',
  [M.ZOOM_OUT]: 'Zoom out',
};
