export enum IconType {
  BOOK = 'BOOK',
  BOOK_SOLID = 'BOOK_SOLID',
  BUILDING_SOLID = 'BUILDING_SOLID',
  FOLDER_OPEN_SOLID = 'FOLDER_OPEN_SOLID',
  GRADUATION_CAP_SOLID = 'GRADUATION_CAP_SOLID',
  ID_BADGE_SOLID = 'ID_BADGE_SOLID',
  MAP_SOLID = 'MAP_SOLID',
  USERS_SOLID = 'USERS_SOLID',
}
