# Konfigurace fazet a dialogu pro jejich zobrazeni
# 
# Každá fazeta se skládá z volitelné podmínky when, 
# která určuje, kdy se fazeta zobrazí a vlastní definice
# fazety.
#
# Podmínka when je vázána na typ apu a případně na sadu
# prvků popisu a jejich hodnot vybraných v jiných fazetách.
# Toto umožňuje zobrazit fazetu například pro určitý druh 
# archiválie.
#
# Fazeta má definován typ (type). Dostupné typy fazet jsou:
# - FULLTEXT - jednoduchý filter na textovou hodnotu
# - ENUM - výběr z 0..n výčtových hodnot, funguje jako OR
# - MULTI_REF - odkaz na více archivních entit, výběr pomocí našeptávače, funguje jako OR
# - UNITDATE - datace, výběr z připravených intervalů nebo ruční zadání
# - MULTI_REF_EXT - odkaz na více archivních entit, výběr pomocí našeptávače, funguje jako OR, 
#   kombinace s podřízenými podmínkami, musí platit ve stejném partu
#
facets:
  # Nazev AS
  # Zdroj je text
  - when:
      apuType: FUND
    # Druh fazety
    type: FULLTEXT
    # zdrojovy itemtype
    source: TITLE
    # Kdy se zobrazi ALWAYS | DETAIL
    display: ALWAYS
    # Nastavení tooltipu k celé fazetě
    tooltip: Zadejte název nebo část názvu archivního souboru
    # Podrobný popis fazety v části filtrů
    description: Filter dle názvu archivního souboru. Je možné zadat část názvu archivního souboru.
    # Pokud bude nutne specializovat
    #   title: Název AS ??

  # Archiv kam patri AS
  # je jich malo
  - when:
      apuType: FUND
    # Druh fazety
    # Lze mit vice vybranych polozke (OR)
    type: ENUM
    # zdrojovy itemtype
    source: INST_REF
    # Počet standardně zobrazených itemů - sbalená varianta
    # displayedItems: 10
    # Max pocet zobrazenych itemu - při rozbalení
    # 0 nebo nenastaveno, znamena bez limitu
    # maxDisplayedItems: 4
    # Způsob řazení položek (těch, které nejsou uvedeny explicitně)
    # orderBy: FREQ | ASC
    #   FREQ - dle počtu, více jsou první
    #   ASC - dle abecedy
    orderBy: ASC
  - when:
      apuType: FUND
    type: FULLTEXT
    source: CISLO_NAD
    display: DETAIL
  - when:
      apuType: FUND
    type: FULLTEXT
    source: FUND_MARK
  # Puvodce AS
  # Zdroj je odkaz na APU
  - when:
      apuType: FUND
    # Druh fazety
    # Výběr více odkazovaných APU, funguje jako OR
    type: MULTI_REF
    # zdrojovy itemtype
    source: ORIGINATOR_REF
  - when:
      apuType: FUND
    # Druh fazety
    type: UNITDATE
    # zdrojovy itemtype
    source: UNIT_DATE
  - when:
      apuType: FUND
    # Druh fazety
    # Výběr více odkazovaných APU, funguje jako OR
    type: MULTI_REF
    # zdrojovy itemtype
    source: ORIG_PLACES_REF

# 
# Archivalie
#

# Druh archivalie
  - when:
      apuType: ARCH_DESC
    type: ENUM
    source: UNIT_TYPE
    display: ALWAYS
    description: Výběr druhu archivního materiálu
    displayedItems: 10
    maxDisplayedItems: 100
    # Volitelná nápověda k položkám ve fazetách
    # Zobrazuje se při najetí na položku
    orderBy: FREQ
    tooltips:
      - value: technický výkres
        tooltip: technické výkresy staveb a výrobků
      - value: pohlednice
        tooltip: pohlednice vzniklé tiskovou technikou
      - value: pohlednice
        tooltip: pohlednice vzniklé tiskovou technikou
      - value: kinematografický záznam
        tooltip: kinematografická díla v analogové i digitální podobě
      - value: zvukový záznam
        tooltip: zvuková díla v analogové i digitální podobě
      - value: úřední kniha
        tooltip: vč. úředních kronik
      - value: rukopis
        tooltip: vč. neúředních kronik
      - value: listina do roku 1850
        tooltip: listiny a listy
      - value: listina po roce 1850
        tooltip: listiny a listy
      - value: plakát
        tooltip: tištěné plakáty
      - value: předmět faleristické povahy
        tooltip: odznaky apod.
    order:
      - matrika
      - kroniky
      - stavební dokumentace
      - evidence nemovitostí
      - evidence obyvatel
      - evidence školní docházky
      - mapa
      - fotografie na papírové podložce
      - fotografická deska
      - technický výkres

# Druh zaznamu
  - when:
      all:
        - apuType: ARCH_DESC
        - filter: UNIT_TYPE
          value: matrika
    type: ENUM
    source: RECORD_TYPE
    display: ALWAYS
    orderBy: ASC

# Datace
  - when:
      apuType: ARCH_DESC
    tooltip: Datace fyzického vzniku
    description: Datace fyzického vzniku
    type: UNITDATE
    source: UNIT_DATE
    display: ALWAYS

  - when:
      apuType: ARCH_DESC
    type: UNITDATE
    source: DATE_OF_CONTENT
    display: DETAIL

  - when:
      apuType: ARCH_DESC
    description: "zarhnuje datace: deklarovaná, vzniku předlohy, vzniku kopie, zpečetění, vydání listiny, insertu/transeptu, vzniku matrice, užívání typáře, vydání dokumentu, reambulace mapy, pořízení obrazového záznamu, pořízení filmového / zvukového záznamu, udělení / propůjčení faleristického předmětu, předání faleristického předmětu, odnětí / vrácení faleristického předmětu"
    type: UNITDATE
    source: DATE_OTHER
    display: DETAIL

# Identifikace archiválie
  - when:
      apuType: ARCH_DESC
    type: FULLTEXT
    source: UNIT_ID_INDEX
    description: "Referenční označení a neplatné referenční označení"
    display: DETAIL
  - when:
      apuType: ARCH_DESC
    type: FULLTEXT
    description: pořadové číslo, signatura přidělená při zpracování archiválie, přidělená při předchozím zpracování archiválie, přírůstkové číslo, neplatné inventární číslo, neplatné ukládací číslo, pořadové číslo pro tisk, uložení v digitálním archivu
    source: OTHER_ID_PROC_INDEX
    display: DETAIL
  - when:
      apuType: ARCH_DESC
    type: FULLTEXT
    description: signatura přidělená původcem, číslo jednací, značka spisu, spisový znak, ukládací znak, číslo vložky úřední knihy, díl, část, pořadí vydání jednotky popisu, matriční číslo propůjčeného vyznamenání, nakladatelské číslo, číslo negativu, číslo produkce CD, kód ISBN, ISSN, ISMN
    source: OTHER_ID_ORIG_INDEX
    display: DETAIL
  - when:
      apuType: ARCH_DESC
    type: ENUM
    source: LANGUAGE
    display: DETAIL
  - when:
      apuType: ARCH_DESC
    type: FULLTEXT
    source: STORAGE_COND
    display: DETAIL
  - when:
      apuType: ARCH_DESC
    type: FULLTEXT
    source: SCALE
    display: DETAIL

# Instituce
  - when:
      apuType: ARCH_DESC
    type: ENUM
    source: FUND_INST_REF
    display: ALWAYS
# Archivní soubor
  - when:
      apuType: ARCH_DESC
    type: MULTI_REF
    source: FUND_REF
    display: ALWAYS

# Role entit
  - when:
      apuType: ARCH_DESC
    # Druh fazety
    type: MULTI_REF_EXT
    # zdrojovy itemtype
    source: AP_VIRT_REF
    maxItems: 30
    includeItems:
      - ITEM_TITLE
      - AP_REF
      - ENTITY_ROLE_1
      - ENTITY_ROLE_2
      - ENTITY_ROLE_4
      - ENTITY_ROLE_5
      - ENTITY_ROLE_10
      - ENTITY_ROLE_6
      - ENTITY_ROLE_7
      - ENTITY_ROLE_8
      - ENTITY_ROLE_9
      - ENTITY_ROLE_11
      - ENTITY_ROLE_3
      - ENTITY_ROLE_12
      - ENTITY_ROLE_13
      - ENTITY_ROLE_14
      - ENTITY_ROLE_15
      - ENTITY_ROLE_16
      - ENTITY_ROLE_17
      - ENTITY_ROLE_18
      - ENTITY_ROLE_19
      - ENTITY_ROLE_20
      - ENTITY_ROLE_21
      - ENTITY_ROLE_22
      - ENTITY_ROLE_23
      - ENTITY_ROLE_24
      - ENTITY_ROLE_25
      - ENTITY_ROLE_26
      - ENTITY_ROLE_27
      - ENTITY_ROLE_28
      - ENTITY_ROLE_29
      - ENTITY_ROLE_30
      - ENTITY_ROLE_31
      - ENTITY_ROLE_32
      - ENTITY_ROLE_33
      - ENTITY_ROLE_34
      - ENTITY_ROLE_35
      - ENTITY_ROLE_36
      - ENTITY_ROLE_37
      - ENTITY_ROLE_38
      - ENTITY_ROLE_39
      - ENTITY_ROLE_40
      - ENTITY_ROLE_41
      - ENTITY_ROLE_42
      - ENTITY_ROLE_43
      - ENTITY_ROLE_44
      - ENTITY_ROLE_45
      - ENTITY_ROLE_46
      - ENTITY_ROLE_47
      - ENTITY_ROLE_48
      - ENTITY_ROLE_49
      - ENTITY_ROLE_50
      - ENTITY_ROLE_51
      - ENTITY_ROLE_52
      - ENTITY_ROLE_53
      - ENTITY_ROLE_54
      - ENTITY_ROLE_55
      - ENTITY_ROLE_56
      - ENTITY_ROLE_57
      - ENTITY_ROLE_58
      - ENTITY_ROLE_59
      - ENTITY_ROLE_60
      - ENTITY_ROLE_61
      - ENTITY_ROLE_62
      - ENTITY_ROLE_63
      - ENTITY_ROLE_64
      - ENTITY_ROLE_65
      - ENTITY_ROLE_66
      - ENTITY_ROLE_67
      - ENTITY_ROLE_68
      - ENTITY_ROLE_69
      - ENTITY_ROLE_70
      - ENTITY_ROLE_71
      - ENTITY_ROLE_72

  # technika, adjustace, nosič a látka záznamu
  - when:
      apuType: ARCH_DESC
    type: FULLTEXT
    source: ITEM_MAT
    display: DETAIL
  # písmo
  - when:
      apuType: ARCH_DESC
    type: FULLTEXT
    source: WRITING
    display: DETAIL

#
# Archivní entity
#
  - when:
      apuType: ENTITY
    type: ENUM
    source: AE_CLASS
    display: ALWAYS
    # Max pocet zobrazenych itemu
    displayedItems: 30
    order:
     - "korporace"
     - "osoba / bytost"
     - "rod / rodina"
     - "geografický objekt"
     - událost
     - "dílo / výtvor"
     - "obecný pojem"
  - when:
      apuType: ENTITY
    type: ENUM
    source: AE_SUBCLASS
    display: ALWAYS
    # Max pocet zobrazenych itemu
    displayedItems: 10
    maxDisplayedItems: 40
    orderBy: FREQ
  - when:
      apuType: ENTITY
    # Druh fazety
    type: MULTI_REF_EXT
    # zdrojovy itemtype
    source: AE_VIRT_REF
    #includeItems:
    #   - ROLE_AUTHOR_X_REF
    #  - ROLE_PUBLICATION_REF
