# Konfigurace fazet a dialogu pro jejich zobrazeni
# 
# Každá fazeta se skládá z volitelné podmínky when, 
# která určuje, kdy se fazeta zobrazí a vlastní definice
# fazety.
#
# Podmínka when je vázána na typ apu a případně na sadu
# prvků popisu a jejich hodnot vybraných v jiných fazetách.
# Toto umožňuje zobrazit fazetu například pro určitý druh 
# archiválie.
#
# Fazeta má definován typ (type). Dostupné typy fazet jsou:
# - FULLTEXT - jednoduchý filter na textovou hodnotu
# - ENUM - výběr z 0..n výčtových hodnot, funguje jako OR
# - MULTI_REF - odkaz na více archivních entit, výběr pomocí našeptávače, funguje jako OR
# - UNITDATE - datace, výběr z připravených intervalů nebo ruční zadání
# - MULTI_REF_EXT - odkaz na více archivních entit, výběr pomocí našeptávače, funguje jako OR, 
#   kombinace s podřízenými podmínkami, musí platit ve stejném partu
#
facets:
  # Nazev AS
  # Zdroj je text
  - when:
      apuType: FUND
    # Druh fazety
    type: FULLTEXT
    # zdrojovy itemtype
    source: TITLE
    # Kdy se zobrazi ALWAYS | DETAIL
    display: ALWAYS
    # Pokud bude nutne specializovat
    #   title: Název AS ??

  # Archiv kam patri AS
  # je jich malo
  - when:
      apuType: FUND
    # Druh fazety
    # Lze mit vice vybranych polozke (OR)
    type: ENUM
    # zdrojovy itemtype
    source: INST_REF
    # Max pocet zobrazenych itemu
    maxItems: 10
  - when:
      apuType: FUND
    type: FULLTEXT
    source: CISLO_NAD
  - when:
      apuType: FUND
    type: FULLTEXT
    source: FUND_MARK
  # Puvodce AS
  # Zdroj je odkaz na APU
  - when:
      apuType: FUND
    # Druh fazety
    # Výběr více odkazovaných APU, funguje jako OR
    type: MULTI_REF
    # zdrojovy itemtype
    source: ORIGINATOR_REF
  - when:
      apuType: FUND
    # Druh fazety
    type: UNITDATE
    # zdrojovy itemtype
    source: UNIT_DATE

# 
# Archivalie
#

# Druh archivalie
  - when:
      apuType: ARCH_DESC
    type: ENUM
    source: UNIT_TYPE
    display: ALWAYS
    maxItems: 30
    order:
      - matrika
      - kniha

# Druh zaznamu
  - when:
      all:
        - apuType: ARCH_DESC
        - filter: UNIT_TYPE
          value: matrika
    type: ENUM
    source: RECORD_TYPE
    display: ALWAYS
    maxItems: 30

# Datace
  - when:
      apuType: ARCH_DESC
    type: UNITDATE
    source: UNIT_DATE
    display: ALWAYS

# Identifikace archiválie
  - when:
      apuType: ARCH_DESC
    type: FULLTEXT
    source: OTHER_ID
    display: DETAIL

# Instituce
  - when:
      apuType: ARCH_DESC
    type: ENUM
    source: FUND_INST_REF
    display: ALWAYS

# Role entit
  - when:
      apuType: ARCH_DESC
    # Druh fazety
    type: MULTI_REF_EXT
    # zdrojovy itemtype
    source: AP_REF
    facets:
      - type: ENUM
        # zdrojovy itemtype
        source: ROLE
        # Max pocet zobrazenych itemu
        maxItems: 30

#
# Archivní entity
#
  - when:
      apuType: ENTITY
    type: ENUM
    source: AE_CLASS
    display: ALWAYS
    # Max pocet zobrazenych itemu
    maxItems: 30
    order:
     - "korporace"
     - "osoba / bytost"
     - "rod / rodina"
     - "geografický objekt"
     - událost
     - "dílo / výtvor"
     - "obecný pojem"
  - when:
      apuType: ENTITY
    type: ENUM
    source: AE_SUBCLASS
    display: ALWAYS
    # Max pocet zobrazenych itemu
    maxItems: 30
  - when:
      apuType: ENTITY
    # Druh fazety
    type: MULTI_REF_EXT
    # zdrojovy itemtype
    source: AE_REL_REF
    facets:
      - type: ENUM
        # zdrojovy itemtype
        source: AE_REL_TYPE
        # Max pocet zobrazenych itemu
        maxItems: 5
