variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

build-doc:
  image: $CI_REGISTRY/lightcomp/docker-images/sphinxdoc7:latest
  stage: build
  tags:
   - docker
  script:
    - rm -f -r ./aron-doc
    - mkdir aron-doc
    - cd doc
    - make html
    - cd build/html 
    - mv * ../../../aron-doc/
    - cd ../../..
  artifacts:
    paths:
      - aron-doc
  only:
    - master

deploy-portal-user-doc:
  tags:
   - docker
   - shell
   - zip
  stage: deploy
  image: $CI_REGISTRY/lightcomp/docker-images/alpine-ssh-client:latest
  script:
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa,ecdsa,ed25519 vlas1.lightcomp.cz >> "${HOME}/.ssh/known_hosts"
    - rm -f -r ./aron-doc.tar.gz
    - tar czf aron-doc.tar.gz ./aron-doc
    - scp aron-doc.tar.gz cdrobot@vlas1.lightcomp.cz:/home/cdrobot/deploy
    - ssh cdrobot@vlas1.lightcomp.cz "./deploy-aron-doc.sh" $CI_COMMIT_REF_NAME
  only:
    - master
