variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - pip install sphinx sphinx-rtd-theme
    - rm -f -r ./aron-doc
    - mkdir aron-doc
    - cd doc    
    - make html
    - cd build/html 
    - mv * ../../../aron-doc/
    - cd ../../..
    - cd src/transfagent
#    - export JAVA_HOME=/etc/alternatives/jre_11
#    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - aron-doc
  only:
    - master

deploy-portal-user-doc:
  stage: deploy
  script:
    - rm -f -r ./aron-doc.tar.gz
    - tar czf aron-doc.tar.gz ./aron-doc
    - scp aron-doc.tar.gz cdrobot@frnk.lightcomp.cz:/home/cdrobot/deploy
    - ssh cdrobot@frnk.lightcomp.cz "./cdscripts/deploy-aron-doc.sh"
  only:
    - master
