packageExtensions:
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
  react-draggable@*:
    peerDependenciesMeta:
      "@types/react":
        optional: true
  react-intl@*:
    peerDependenciesMeta:
      "@types/react":
        optional: true
  webpack@*:
    peerDependencies:
      webpack-cli: "*"
    peerDependenciesMeta:
      webpack-cli:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
