spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aron
    username: uas
    password: vuji61oilo
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        globally_quoted_identifiers: true
  liquibase:
    changeLog: classpath:/dbchangelog.xml

server:
  port: 8080
  servlet:
    context-path: /aron/api

file:
  path: target/data
  maxSize: 10485760
multipart:
  maxFileSize: 10MB

environment: Lukess