---
openapi: 3.0.2
info:
  version: 1.0.0
  title: ARON Core Service API
servers:
  - url: https://localhost:3000/
tags:
  - name: Aron
paths:
  /test:
    get:
      tags:
        - Aron
      summary: test	
      description: ""
      operationId: test
      responses:
        "200":
          description: Success

  '/apu/{id}/entity':
    get:
      tags:
        - Aron
      summary: Get object with given id
      operationId: getApu
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApuEntity'

  /apu/listview:
    post:
      tags:
        - Aron
      operationId: listView
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'search-api.yaml#/components/schemas/Params'
        required: true
      responses:
        '200':
          description: default response
          content:
            'application/json':
              schema:
                $ref: 'search-api.yaml#/components/schemas/SimpleResult'

  /apu/listresults:
    post:
      tags:
        - Aron
      operationId: listResults
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'search-api.yaml#/components/schemas/Params'
        required: true
      responses:
        '200':
          description: default response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/StructuredResults'

  /apu/listsimple:
    post:
      tags:
        - Aron
      operationId: listSimple
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'search-api.yaml#/components/schemas/Params'
        required: true
      responses:
        '200':
          description: default response
          content:
            'application/json':
              schema:
                $ref: 'search-api.yaml#/components/schemas/SimpleResult'

  '/apu/views':
    get:
      tags:
        - Aron
      summary: Get views for given APU ids
      operationId: getViews
      parameters:
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
          style: simple
          explode: false
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApuEntityView'

  '/apu/{id}/view':
    get:
      tags:
        - Aron
      summary: Get view for given APU id
      operationId: getView
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApuEntityView'

  '/apu/{id}/related/{direction}':
    get:
      tags:
        - Aron
      summary: Get related nodes for given APU in specified direction
      operationId: getRelatedNodes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: direction
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApuEntityTreeViewDto'

  /apu/list:
    post:
      tags:
        - Aron
      summary: List objects satisfying given params
      operationId: list
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'search-api.yaml#/components/schemas/Params'
        required: true
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: 'search-api.yaml#/components/schemas/SimpleResult'                

components:
  schemas:                
    ApuEntity:
      required:
        - id
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        result:
          type: string
        permalink:
          type: string
        order:
          type: integer
          format: int32
        published:
          type: boolean
        depth:
          type: integer
          format: int32
        pos:
          type: integer
          format: int32
        childCnt:
          type: integer
          format: int32
        indexed:
          type: boolean
        parent:
          $ref: '#/components/schemas/ApuEntity'
        parts:
          type: array
          items:
            $ref: '#/components/schemas/ApuPart'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/ApuAttachment'
        digitalObjects:
          type: array
          items:
            $ref: '#/components/schemas/DigitalObject'
        type:
          type: string
          enum:
            - ARCH_DESC
            - COLLECTION
            - ENTITY
            - FINDING_AID
            - FUND
            - INSTITUTION
    ApuPart:
      required:
        - id
      type: object
      properties:
        id:
          type: string
        value:
          type: string
        type:
          type: string
        childParts:
          type: array
          items:
            $ref: '#/components/schemas/ApuPart'
        items:
          type: array
          items:
            $ref: '#/components/schemas/ApuPartItem'
    ApuPartItem:
      required:
        - id
      type: object
      properties:
        id:
          type: string
        value:
          type: string
        visible:
          type: boolean
        href:
          type: string
        type:
          type: string
        label:
          type: string
    DigitalObject:
      required:
        - id
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        permalink:
          type: string
        order:
          type: integer
          format: int32
        licenseCode:
          type: string
        files:
          type: array
          items:
            $ref: '#/components/schemas/DigitalObjectFile'
    DigitalObjectFile:
      required:
        - id
      type: object
      properties:
        id:
          type: string
        permalink:
          type: string
        order:
          type: integer
          format: int32
        type:
          type: string
          enum:
            - PUBLISHED
            - THUMBNAIL
            - TILE
        file:
          $ref: '#/components/schemas/File'
        name:
          type: string
        referencedFile:
          type: string
        contentType:
          type: string
        size:
          type: integer
          format: int64
        selected:
          type: boolean
    File:
      required:
        - id
      type: object
      properties:
        id:
          type: string
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        deleted:
          type: string
          format: date-time
        name:
          type: string
        contentType:
          type: string
        size:
          type: integer
          format: int64
        permanent:
          type: boolean
    ApuAttachment:
      required:
        - id
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        order:
          type: integer
          format: int32
        file:
          $ref: '#/components/schemas/DigitalObjectFile'
    ApuEntityView:
      required:
        - id
        - name
        - order
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        order:
          type: integer
          format: int32
    ApuEntityTreeViewDto:
      required:
        - id
        - name
        - description        
        - depth
        - pos
        - childCnt
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        depth:
          type: integer
          format: int32
          nullable: false
        pos:
          type: integer
          format: int32
          nullable: false
        childCnt:
          type: integer
          format: int32
          nullable: false
    ResultRowItemValue:
      type: object
      required:
        - v
      properties:
        v:
          type: string
        id:
          type: string
    ResultRowItem:
      type: object
      required:
        - t
        - v
      properties:
        t:
          type: string
        v:
          type: array
          items:
            $ref: '#/components/schemas/ResultRowItemValue'
    StructuredResult:
      type: object
      required:
        - id
        - t
        - l
      properties:
        id:
          type: string
        t:
          type: string
        tn:
          type: string
        tnLink:
          type: string
        l:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/ResultRowItem'
    StructuredResults:
      description: Structured results
      type: object
      allOf:
      - $ref: "#/components/schemas/ResultBase"
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/StructuredResult'
